config/routes.rb
Rails.application.routes.draw do

  root 'dig_top#home'
  get 'dig_home/dighome'
  get 'dig_home/dig_index'
  get 'dig_top/setumei'


  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  
  devise_for :users

  resource :profiles
  resources :game, only: %i(index show)

  resources :users do
    resources :tasks, only: %i(index)
  end
  
  resources :endshow, only: %i(index)
  resources :chat_rooms, only: %i(index destroy)

  resources :tasks do
    resources :chat_rooms, only: %i(index create)
    resources :work_schedules #resource 単数でｉｄを作らない
    resource :done, only: %i(index update)
  end

  namespace :work_schedules do
    resources :positions, only: %i(update)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_one_attached :image
  belongs_to :task
  belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :work_schedules
  has_many :comments
  has_many :todos, -> { order("done ASC, position ASC") }, dependent: :destroy
  has_one_attached :image
  
  enum status: { todo: 0, doing: 1, done: 2 }
  validates :name, presence: true
  
  def complete
    ActiveRecord::Base.transaction do
    done!
    todos.update_all(done: true)
    end
    true
  rescue => e
    false
  end
  
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :task
  acts_as_list scope: [:task_id]

  validates :position, numericality: { only_integer: true, allow_nil: true }
  validates :content, presence: true
  validates :done, inclusion: { in: [true, false] }

  after_initialize :set_default, if: :new_record?

  private

  def set_default
    self.done = false if self.done.blank?
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks
  has_many :comments
  has_one_attached :avatar
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:trackable,
         :lockable, :timeoutable
  
  validates :name, uniqueness: true

  def email_required?
    false
  end
          
  def email_changed?
    false
  end      
end

app/models/work_schedule.rb
class WorkSchedule < ApplicationRecord
  belongs_to :task

  acts_as_list
  validates :name, presence: true

  enum status: { pending: 0, done: 1 }
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/dig_home_controller.rb
class DigHomeController < ApplicationController
before_action :authenticate_user!
#before_action :logged_in_user, only: [:jikou, :jikou_end, :chat_room, :minnna, :proces]deviseで自動生成
PER = 5
  
  def dighome
    @alluser = User.all
    @alltask = Task.order(created_at: :desc).limit(30)
  end

  def dig_index
    @users = User.order(created_at: :asc).page(params[:page]).per(PER)
    @user = User.first
  end
  
  def show
  end
  
  def chat_room
     @task = current_user.tasks(name)
  end
  
private
  def user_search_params
    params.fetch(:search, {}).permit(:name)
  end

end

app/controllers/dig_top_controller.rb
class DigTopController < ApplicationController
  layout 'digtop'
  
  def home

  end

  def help
  end
  
  def setumei
    render layout: 'setumei'
  end  
end

app/controllers/dones_controller.rb
class DonesController < ApplicationController
before_action :set_task, only: %i(update)

  def show
      @user = User.find(params[:user_id])
  end

  def update
    @task.done!
    redirect_to endshow_index_path
  end

  private

  def set_task
    @task = Task.find(params[:task_id])
  end
end

app/controllers/endshow_controller.rb
class EndshowController < ApplicationController
    before_action :authenticate_user!
    PER = 5

    def index      
      @tasks = Task.done.page(params[:page]).per(PER)
    end
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def index
  
  end
  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to tasks_path if user_signed_in?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :check_ten_todo, only: [:create]
  before_action :set_task, only: [:update]
  before_action :set_user, only: %i(index)
  
  def index
    @user = params[:user_id].present? ? @user : current_user
    @tasks = @user.tasks.todo.order(updated_at: :desc).page(params[:page])
  end
  
  def new
    @task = current_user.tasks.build
  end 
  
  def show
    @user = current_user
    @tasks = Task.find(params[:id])
  end
  
  def edit
  end

  def endshow_index
    @tasks = current_user.tasks.done.order(updated_at: :desc).page(params[:page])
  end

  def create
    @task = current_user.tasks.build(task_params)

    if @task.save
      redirect_to task_chat_rooms_path(@task)
      @status = true
    else
      render :new
      @status = false
    end
  end

   def update
     if @task.complete
       redirect_to tasks_path
     else
       render :index
     end
   end

  # DELETEs/1
  def destroy
    @task = current_user.tasks.find(params[:id])
    @task.destroy
    redirect_to user_path(current_user), notice: '削除されました'
  end

  private

  def task_params
    params.require(:task).permit(:user_id, :name)
  end
  
  def set_task
    @task = current_user.tasks.find(params[:id])
  end
  
  def check_ten_todo
    redirect_to root_path, notice: 'やりたい事は10個以上を登録できません。全行程終了してから再度お試しください。' if current_user.tasks.todo.size == 10
  end

  def set_user
    @user = User.find(params[:user_id]) if params[:user_id].present?
  end
  
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, except: [:index]
  before_action :set_todo, only: [:show, :edit, :update, :destroy, :sort]

  #endshowの工程ボタンからここへ
  def index 
    @task = Task.find(params[:task_id])
    render 'dones/show'
  end

  # GET /todos/new
  def new
    @todo = @task.todos.new
  end

  # GET /todos/1/edit
  def edit
  end
  
  def sort
  end


  # POST /todos
  def create
    @todo = @task.todos.new(todo_params)

    if @todo.save
       @status = true
    else
       @status = false
    end
  end

  # PATCH/PUT /todos/1
  def update
    if @todo.update(todo_params)
       @status = true
    else
       @status = false
    end
  end

  # DELETE /todos/1
  def destroy
    @todo.destroy
    redirect_to todos_url, notice: 'Todo was successfully destroyed.'
  end

  private

  def set_task
    @task = current_user.tasks.find_by(id: params[:task_id])
    redirect_to(tasks_url, alert: "ERROR!!") if @task.blank?
  end

  def set_todo
    @todo = @task.todos.find_by(id: params[:id])
  end


    def todo_params
      params.require(:todo).permit(:content, :task_id, :position, :done)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :authenticate_user!

  def index
    @users = params[:name].present? ? User.where('name LIKE ?', "%#{params[:name]}%") : User.none
  end
  
  def show
    @user = User.find(params[:id])
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bs4_bgcolor_for(flash_key)
     case flash_key
     when "success"
       "alert-success"
     when "error"
       "alert-danger"
     when "alert"
       "alert-warning"
     when "notice"
       "alert-info"
     else
       flash_key.to_s
     end
  end
  
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, options = { size: 80 })
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/game/index.html.erb
<%= javascript_pack_tag 'game/javagame' %>
<button id="btn">戦闘</button>
<%= link_to "リセットする", game_index_path, id: "reset" %>
<div id="suraimu"><%= image_pack_tag "スライム.png", width:"200px",hight:"200px" %></div>

<ul id="list"></div>
<div id="exit"></div>

app/views/game/show.html.erb
<h1 id="movetext">テキスト</h1>
<button id="movebtn">そんな動くのΣ（・□・；）</button>


<script>
  $('#movetext').text('ぐゎぐゎ');

  $('#movebtn').on('click', () => {
    $('h1').css('color', 'red');
    $('h1').animate({left: '80%'}, 1000);
    $('h1').animate({left: '40%'}, 1500);
    $('h1').animate({fontSize: '8em'}, 500);
    $('h1').animate({left: '60%',top: '40%'}, 300);
    $('h1').animate({left: 0,top: 0,fontSize: '1em'}, 1000);
  })
</script>

app/views/tasks/_form.html.erb
<div class="modal fade" id="taskModal" tabindex="-1" role="dialog" aria-labelledby="taskModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_with(model: task, remote: true) do |form| %>
        <div class="modal-header">
          <h5 class="modal-title" id="taskModal"><%= "#{params[:action].camelize} #{task.model_name.human}" %></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <% if task.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>
              <ul>
                <% task.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="field">
            <%= form.label :name %>
            <%= form.text_field :name %>
          </div>
        </div>
          <div class="modal-footer actions">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= form.submit %>
        </div>
      <% end %>
    </div>
  </div>
</div>  

app/views/tasks/_task.html.erb
  <div class="card bg-light d-inline-block text-wrap h-100 mx-1 task-card"
    data-model_name="<%= Task.model_name.singular %>"
    data-id="<%= task.id %>">
    <div class="d-flex flex-column h-100" style="width: 35rem; min-width: 25rem;">
      <div class="font-weight-bold px-4 py-2 task-header">
        <div class="pr-5">
          <%= task.name %> 
        </div>
        <div class="text-right position-absolute" style="top: 4px; right: 4px">
          <%= link_to(new_task_todo_path(task), title: "New TODO", class: "btn px-0", remote: true) do %><i class="fas fa-plus align-middle"></i><% end %>
          <div class="btn-group">
            <button type="button" class="btn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-ellipsis-v align-middle"></i>
            </button>
            <div class="dropdown-menu dropdown-menu-right text-middle">
              <%= link_to "Edit", edit_task_path(task), class: "dropdown-item", remote: true %>
            </div>
          </div>
        </div>
      </div>
      <div class="card-body px-2 pb-2 pt-0 overflow-auto todo-cards">
        <%= render partial: "todos/todo", collection: task.todos, as: :todo %>
      </div>
    </div>
    <%= link_to "全行程終了", task_path(task), method: :patch, class: "btn btn-primary" %>
  </div>

app/views/tasks/index.html.erb
<div class="task-title-area px-3">
  <h2>工程作成    提案者：<%= @user.name %> <%= link_to "back",:back %></h2>
  <%= link_to "#", title: "New", class: "btn p-0 text-dark", local: true do %>
</div>
  <div class="pt-3 p-1 text-nowrap task-index-area" id="tasksIndex">
    <%= render @tasks %>
  <% end %> 
</div>

app/views/tasks/new.html.erb
<div id="main-title">
  <h1>実行したい事作成</h1>
</div>
<div class= "task-new">
  <div id="form">
    <%= form_with model: @task, local: true, class: 'input-group' do |form| %>
      <%= form.text_field :name, class: 'form-control', placeholder:"やりたいことを入力" %>
      <%= form.submit "チャットルームへ", class: 'input-group-text' %>
      <% end %>
  </div>
<div class= "wrapper grid">
  <div class="item">
    <%= image_pack_tag "706460_s.jpg", width:"400px",hight:"400px", alt:"世界一周旅行" %>
    <p>世界一周旅行に行きたい</p>
  </div>    
  <div class="item">
    <%= image_pack_tag "1556061_s.jpg", width:"400px",hight:"400px",alt:"スポーツ" %>
    <p>スポーツをしたい、サークルをつくりたい</p>
  </div>          
  <div class="item">
    <%= image_pack_tag "1028007_s.jpg", width:"400px",hight:"400px",alt:"ゲーム" %>
    <p>ゲームを作りたい、ゲームの攻略</p>
  </div>          
  <div class= "item">
    <%= image_pack_tag "3146890_s.jpg", width:"400px",hight:"400px",alt:"ファーストクラス" %>
    <p>ファーストクラスに乗ってみたい</p>
  </div>          
  <div class="item">
    <%= image_pack_tag "1927236_s.jpg", width:"400px",hight:"400px",alt:"ジムトレーニング" %>
    <p>体づくりの目標がある</p>
  </div>          
  <div class="item">
    <%= image_pack_tag "4029283_s.jpg", width:"400px",hight:"400px",alt:"他の人のを見て真似る" %>
    <p>他の実行した事をみて参考にする</p>
  </div>
  <div class="item">
    <%= image_pack_tag "1802919_s.jpg", width:"400px",hight:"400px",alt:"店を出す" %>
    <p>店を出したい、ネットサイトで物を売りたい</p>
  </div>      
  <div class="item">
    <%= image_pack_tag "3336161_s.jpg", width:"400px",hight:"400px",alt:"他の職場体験" %>
    <p>他の職業体験してみたい</p>
  </div>      
  <div class="item">
    <%= image_pack_tag "2067084_s.jpg", width:"400px",hight:"400px",alt:"馬を乗りたい" %>
    <p>馬を自由に乗りこなしたい</p>
  </div>      
  <div class="item">
    <%= image_pack_tag "1317236_s.jpg",width:"400px",hight:"400px", alt:"仕事の目標" %>
    <p>仕事の目標、資格の目標がある</p>
  </div>    
  <div class="item">
    <%= image_pack_tag "2138561_s.jpg",width:"400px",hight:"400px", alt:"学生体験" %>
    <p>学生に戻りたい（学校を借りる、文化祭をする）</p>
  </div>
  <div class="item">
    <%= image_pack_tag "3569432_s.jpg",width:"400px",hight:"400px", alt:"会いたい" %>
    <p>会ってみたい人がいる</p>
  </div> 
  <div class="item">
    <iframe width="400px" height="400px" src="https://www.youtube.com/embed/aqa9h-nL-TA?start=10" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <p>ユーチューブをはじめたい</p>
  </div>
</div>


app/views/tasks/show.html.erb
<div class="task-title-area px-3">
  <h2>工程作成    提案者：<%= @user.name %></h2>
  <%= link_to new_task_path, title: "New", class: "btn p-0 text-dark", local: true do %>
  <span class="align-middle"></span>
</div>
  <div class="pt-3 p-1 text-nowrap task-index-area" id="tasksIndex">
    <%= render @tasks %>
  <% end %> 
</div>