config/routes.rb
Rails.application.routes.draw do

  root 'dig_top#home'
  get 'dig_home/dighome'
  get 'dig_home/dig_index'
  get 'dig_top/setumei'


  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  
  devise_for :users

  resource :profiles
  resources :game, only: %i(index show)

  resources :users do
    resources :tasks, only: %i(index)
  end
  
  resources :endshow, only: %i(index)
  resources :chat_rooms, only: %i(index destroy)

  resources :tasks do
    resources :chat_rooms, only: %i(index create)
    resources :work_schedules #resource 単数でｉｄを作らない
    resource :done, only: %i(index update)
  end

  namespace :work_schedules do
    resources :positions, only: %i(update)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_one_attached :image
  belongs_to :task
  belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :work_schedules
  has_many :comments
  has_many :todos, -> { order("done ASC, position ASC") }, dependent: :destroy
  has_one_attached :image
  
  enum status: { todo: 0, doing: 1, done: 2 }
  validates :name, presence: true
  
  def complete
    ActiveRecord::Base.transaction do
    done!
    todos.update_all(done: true)
    end
    true
  rescue => e
    false
  end
  
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :task
  acts_as_list scope: [:task_id]

  validates :position, numericality: { only_integer: true, allow_nil: true }
  validates :content, presence: true
  validates :done, inclusion: { in: [true, false] }

  after_initialize :set_default, if: :new_record?

  private

  def set_default
    self.done = false if self.done.blank?
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks
  has_many :comments
  has_one_attached :avatar
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:trackable,
         :lockable, :timeoutable
  
  validates :name, uniqueness: true

  def email_required?
    false
  end
          
  def email_changed?
    false
  end      
end

app/models/work_schedule.rb
class WorkSchedule < ApplicationRecord
  belongs_to :task

  acts_as_list
  validates :name, presence: true

  enum status: { pending: 0, done: 1 }
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/dig_top_controller.rb
class DigTopController < ApplicationController
  layout 'digtop'
  
  def home

  end

  def help
  end
  
  def setumei
    render layout: 'setumei'
  end  
end

app/controllers/dones_controller.rb
class DonesController < ApplicationController
before_action :set_task, only: %i(update)

  def show
      @user = User.find(params[:user_id])
  end

  def update
    @task.done!
    redirect_to endshow_index_path
  end

  private

  def set_task
    @task = Task.find(params[:task_id])
  end
end

app/controllers/endshow_controller.rb
class EndshowController < ApplicationController
    before_action :authenticate_user!
    PER = 5

    def index      
      @tasks = Task.done.page(params[:page]).per(PER)
    end
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def index
  
  end
  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to tasks_path if user_signed_in?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :check_ten_todo, only: [:create]
  before_action :set_task, only: [:update]
  before_action :set_user, only: %i(index)
  
  def index
    @user = params[:user_id].present? ? @user : current_user
    @tasks = @user.tasks.todo.order(updated_at: :desc).page(params[:page])
  end
  
  def new
    @task = current_user.tasks.build
  end 
  
  def show
    @user = current_user
    @tasks = Task.find(params[:id])
  end
  
  def edit
  end

  def endshow_index
    @tasks = current_user.tasks.done.order(updated_at: :desc).page(params[:page])
  end

  def create
    @task = current_user.tasks.build(task_params)

    if @task.save
      redirect_to task_chat_rooms_path(@task)
      @status = true
    else
      render :new
      @status = false
    end
  end

   def update
     if @task.complete
       redirect_to tasks_path
     else
       render :index
     end
   end

  # DELETEs/1
  def destroy
    @task = current_user.tasks.find(params[:id])
    @task.destroy
    redirect_to user_path(current_user), notice: '削除されました'
  end

  private

  def task_params
    params.require(:task).permit(:user_id, :name)
  end
  
  def set_task
    @task = current_user.tasks.find(params[:id])
  end
  
  def check_ten_todo
    redirect_to root_path, notice: 'やりたい事は10個以上を登録できません。全行程終了してから再度お試しください。' if current_user.tasks.todo.size == 10
  end

  def set_user
    @user = User.find(params[:user_id]) if params[:user_id].present?
  end
  
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, except: [:index]
  before_action :set_todo, only: [:show, :edit, :update, :destroy, :sort]

  #endshowの工程ボタンからここへ
  def index 
    @task = Task.find(params[:task_id])
    render 'dones/show'
  end

  # GET /todos/new
  def new
    @todo = @task.todos.new
  end

  # GET /todos/1/edit
  def edit
  end
  
  def sort
  end


  # POST /todos
  def create
    @todo = @task.todos.new(todo_params)

    if @todo.save
       @status = true
    else
       @status = false
    end
  end

  # PATCH/PUT /todos/1
  def update
    if @todo.update(todo_params)
       @status = true
    else
       @status = false
    end
  end

  # DELETE /todos/1
  def destroy
    @todo.destroy
    redirect_to todos_url, notice: 'Todo was successfully destroyed.'
  end

  private

  def set_task
    @task = current_user.tasks.find_by(id: params[:task_id])
    redirect_to(tasks_url, alert: "ERROR!!") if @task.blank?
  end

  def set_todo
    @todo = @task.todos.find_by(id: params[:id])
  end


    def todo_params
      params.require(:todo).permit(:content, :task_id, :position, :done)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :authenticate_user!

  def index
    @users = params[:name].present? ? User.where('name LIKE ?', "%#{params[:name]}%") : User.none
  end
  
  def show
    @user = User.find(params[:id])
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bs4_bgcolor_for(flash_key)
     case flash_key
     when "success"
       "alert-success"
     when "error"
       "alert-danger"
     when "alert"
       "alert-warning"
     when "notice"
       "alert-info"
     else
       flash_key.to_s
     end
  end
  
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, options = { size: 80 })
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/dig_top/home.html.erb
<div class = "digtop">
    <h1>Dig up tool</h1>
    <p>
      やりたかったけど手付かずの事を進めれるページにしたいです、<%= link_to 'サイト説明ページ', dig_top_setumei_path %>を見てください
    </p>
    <div class = "touroku-btn">  
      <%= link_to "登録ページ", new_user_registration_path, class: "btn btn-lg btn-success" %><br>
      <%= link_to "登録済みユーザー", new_user_session_path, class: "btn btn-lg btn-primary" %>
    </div>
</div>

app/views/dig_top/setumei.html.erb
<div class="setumei-wrapper">
	<header class="page-header wraper">
	<%  if user_signed_in?  %>
	<nav>
		<ul class="main-nav">
				<h3><%= link_to image_pack_tag("cooltext382693541664232.png", size:'200x50'), dig_home_dighome_path %></h3>
				<li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
				<li><%= link_to "ホーム", dig_home_dighome_path %></li>         
				<li><%= link_to "プロフィール", profiles_path %></li>
		</ul>
	</nav>

	<% else %>
	<nav>
		<ul class="main-nav">
			<h3><%= link_to image_pack_tag("cooltext382693541664232.png", size:'200x50'), dig_home_dighome_path %></h3>
			<li><%= link_to "プロフィール", profiles_path %></li>
			<li><%= link_to "ログイン", new_user_session_path %></li>
		</ul>
	</nav>
	<% end %>
	</header>

	<div class = "setumei-page">
		<h3>サイトの説明</h3>　
		<p>やりたいのにあきらめてしまってる事や<p>
		<p>一回はやってみたかった事、こういう夢があった等をみんなで協力して実行していけるツールしたいです</p>

		<p>このサイトのユーザー招待は自分の親交のある人を呼んでます、招待したパスワードは教えないでください</p>

		<p>このサイトをきっかけに作りたいサービスやＷＥＢアプリのアイデアがでて作るのも面白いかと
				<p>（例）自分専用のオリジナルショッピングサイトや趣味のサークルサイト</P>
				<p>	個人経営で付き合いのある会社同士の仕事の波を可視化して把握できるサイト（暇な時、忙しい時をマッチングする)</P>
				<p>自分たちの欲しいアイデアグッズを作って、オリジナル商品サイトを作る</p>

		<h3><進め方>	ユーザー登録をする</h3>
		<p>登録ボタンからユーザー名とパスワードを入れてください</p>

		<h3>実行したい事を決める（実行したいことボタンを押す)</h3>
		<p>(入力した内容がタイトルになります)
		<p>その提案者のやりたい事のチャットページが作られる<br>
			（ユーザー登録者はコメントで意見を出し合う右上の工程ページ作成へ）</h3>

		<h3>工程作成ページで内容をまとめる、ドラッグで並び替え可能<br>
				（記入変更は提案者のみ可能）</h3>
				<div class= "item">
				<%= image_pack_tag "task-index.png", width:"800px",hight:"350px", alt:"工程ページ" %>
				</div>
		
		<h3>ホーム画面</h3>
		<div class= "item">
		<%= image_pack_tag "digup-home.png", width:"800px",hight:"350px", alt:"ホーム画面" %>
		</div>
		<p>みんなのやりたい事一覧ボタンから自分含め他のユーザーのチャットや工程ページに行く</p>
		<p>(ホーム画面）今まで実行した事で登録ユーザーの実行した事の工程を参考にできる</p>
		<p>右上のプロフィールから自分のアイコン画像、名前等を変更できます
		<h3>プロフィール設定</h3>
		<p>アイコン設定はＧｒａｖａｔａｒ<a href="https://ja.gravatar.com/">（サイトｕｒｌ)</a>と連携してます<br>
		<a href="https://www.adminweb.jp/wordpress/comment/index10.html">Ｇｒａｖａｔａｒの登録説明</a>（登録方法がわかりやすいページへ移動）</p><br>
		<p>gravatarとはアイコン画像を管理するWebサービスです</p>
	</div>
</div>

app/views/endshow/index.html.erb
<div id="main-title">
  <h1>実行した事一覧</h1>
</div>
<div class = "seach-itiran">
  <div class="kaminari"> <%= paginate @tasks %> </div>

<% @tasks.each do |done| %>
  <div class = "ji-itiran">
    <div class = "ji-koutei">
      <h5><%= done.name %></h5>&emsp;&emsp;
      <%= link_to "終了工程ページへ", task_work_schedules_path(done), class: "btn btn-primary" %>
      
    </div> 
  </div>
<% end %>