config/routes.rb
Rails.application.routes.draw do

  root 'dig_top#home'
  get 'dig_home/dighome'
  get 'dig_home/dig_index'
  get 'dig_top/setumei'


  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  
  devise_for :users

  resource :profiles
  resources :game, only: %i(index show)

  resources :users do
    resources :tasks, only: %i(index)
  end
  
  resources :endshow, only: %i(index)
  resources :chat_rooms, only: %i(index destroy)

  resources :tasks do
    resources :chat_rooms, only: %i(index create)
    resources :work_schedules #resource 単数でｉｄを作らない
    resource :done, only: %i(index update)
  end

  namespace :work_schedules do
    resources :positions, only: %i(update)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks
  has_many :comments
  has_one_attached :avatar
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:trackable,
         :lockable, :timeoutable
  
  validates :name, uniqueness: true

  def email_required?
    false
  end
          
  def email_changed?
    false
  end      
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController

end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController

end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :authenticate_user!

  def index
    @users = params[:name].present? ? User.where('name LIKE ?', "%#{params[:name]}%") : User.none
  end
  
  def show
    @user = User.find(params[:id])
  end

  
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, options = { size: 80 })
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/users/index.html.erb
<div id="main-title">
  <h1>みんなのやりたい事検索</h1>
</div>
<div class = "seach-itiran">
  <%= form_with url: users_path,method: :get, local: true, class: 'input-group' do |f| %>
    <%= f.text_field :name, class: 'form-control', placeholder:"検索したいユーザー名" %>
    <%= f.submit "送信", class: 'input-group-text' %>
  <% end %>
</div>

<% @users.each do |user| %>
  <div id="minna-wrapper">
    <div id= "minna-name">
      <div id="profile-image">
        <%= gravatar_for user, size: 250 %>
      </div>
      <h3><%= user.name %></h3>
    </div>

    <div id="profile-page-wrapper">
    <% if user.tasks.todo.any? %>
      <% user.tasks.todo.each do |task| %>
        <div id="minnna-task-show">
          <h5><%= task.name %></h5>
          <div id="btn-itiran">
            <%= link_to "チャットルームへ", task_chat_rooms_path(task), class: "btn btn-primary" %>
            <%= link_to "工程ページへ", task_work_schedules_path(task), class: "btn btn-success" %>
            <% if current_user.tasks.include?(task) %>
              <%= link_to "削除", task_path(task), method: :delete, 
              data:{ confirm: "この行のやりたい事を削除しますか？"}, class: "btn btn-danger" %>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>


  </div>
<% end %>

app/views/users/mypage.html.erb
<% if user.tasks.todo.any? %>
  <% user.tasks.todo.each do |task| %>
    <div class="seach">
      <h5><%= task.name %></h5>
    </div>
    <div class="btn-itiran">
      <%= link_to "チャットルームへ", task_chat_rooms_path(task), class: "btn btn-primary" %>
      <%= link_to "工程ページへ", user_tasks_path(user), class: "btn btn-successs" %>
    </div>
  <% end %>
<% end %>

app/views/users/show.html.erb
<div id="main-title">
  <h1>自分のページ</h1>
</div>
<div id="minna-wrapper">
  <div id= "minna-name">
    <div id="profile-image">
      <%= gravatar_for @user, size: 250 %>
    </div>
    <h3><%= @user.name %></h3>
  </div>
  <div id="profile-page-wrapper">
    <% if @user.tasks.todo.any? %>
      <% @user.tasks.todo.each do |task| %>
        <div id="minnna-task-show">
          <h5><%= task.name %></h5>
          <div id="btn-itiran">
            <%= link_to "チャットルームへ", task_chat_rooms_path(task), class: "btn btn-primary" %>
            <%= link_to "工程ページへ", task_work_schedules_path(task), class: "btn btn-success" %>
            <% if current_user.tasks.include?(task) %>
              <%= link_to "削除", task_path(task), method: :delete, 
              data:{ confirm: "この行のやりたい事を削除しますか？"}, class: "btn btn-danger" %>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>