config/routes.rb
Rails.application.routes.draw do

  root 'dig_top#home'
  get 'dig_home/dighome'
  get 'dig_home/dig_index'
  get 'dig_top/setumei'


  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  
  devise_for :users

  resource :profiles
  resources :game, only: %i(index show)

  resources :users do
    resources :tasks, only: %i(index)
  end
  
  resources :endshow, only: %i(index)
  resources :chat_rooms, only: %i(index destroy)

  resources :tasks do
    resources :chat_rooms, only: %i(index create)
    resources :work_schedules #resource 単数でｉｄを作らない
    resource :done, only: %i(index update)
  end

  namespace :work_schedules do
    resources :positions, only: %i(update)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_one_attached :image
  belongs_to :task
  belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :work_schedules
  has_many :comments
  has_many :todos, -> { order("done ASC, position ASC") }, dependent: :destroy
  has_one_attached :image
  
  enum status: { todo: 0, doing: 1, done: 2 }
  validates :name, presence: true
  
  def complete
    ActiveRecord::Base.transaction do
    done!
    todos.update_all(done: true)
    end
    true
  rescue => e
    false
  end
  
end

app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :task
  acts_as_list scope: [:task_id]

  validates :position, numericality: { only_integer: true, allow_nil: true }
  validates :content, presence: true
  validates :done, inclusion: { in: [true, false] }

  after_initialize :set_default, if: :new_record?

  private

  def set_default
    self.done = false if self.done.blank?
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks
  has_many :comments
  has_one_attached :avatar
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,:trackable,
         :lockable, :timeoutable
  
  validates :name, uniqueness: true

  def email_required?
    false
  end
          
  def email_changed?
    false
  end      
end

app/models/work_schedule.rb
class WorkSchedule < ApplicationRecord
  belongs_to :task

  acts_as_list
  validates :name, presence: true

  enum status: { pending: 0, done: 1 }
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/dig_home_controller.rb
class DigHomeController < ApplicationController
before_action :authenticate_user!
#before_action :logged_in_user, only: [:jikou, :jikou_end, :chat_room, :minnna, :proces]deviseで自動生成
PER = 5
  
  def dighome
    @alluser = User.all
    @alltask = Task.order(created_at: :desc).limit(30)
  end

  def dig_index
    @users = User.order(created_at: :asc).page(params[:page]).per(PER)
    @user = User.first
  end
  
  def show
  end
  
  def chat_room
     @task = current_user.tasks(name)
  end
  
private
  def user_search_params
    params.fetch(:search, {}).permit(:name)
  end

end

app/controllers/dig_top_controller.rb
class DigTopController < ApplicationController
  layout 'digtop'
  
  def home

  end

  def help
  end
  
  def setumei
    render layout: 'setumei'
  end  
end

app/controllers/dones_controller.rb
class DonesController < ApplicationController
before_action :set_task, only: %i(update)

  def show
      @user = User.find(params[:user_id])
  end

  def update
    @task.done!
    redirect_to endshow_index_path
  end

  private

  def set_task
    @task = Task.find(params[:task_id])
  end
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def index
  
  end
  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to tasks_path if user_signed_in?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :check_ten_todo, only: [:create]
  before_action :set_task, only: [:update]
  before_action :set_user, only: %i(index)
  
  def index
    @user = params[:user_id].present? ? @user : current_user
    @tasks = @user.tasks.todo.order(updated_at: :desc).page(params[:page])
  end
  
  def new
    @task = current_user.tasks.build
  end 
  
  def show
    @user = current_user
    @tasks = Task.find(params[:id])
  end
  
  def edit
  end

  def endshow_index
    @tasks = current_user.tasks.done.order(updated_at: :desc).page(params[:page])
  end

  def create
    @task = current_user.tasks.build(task_params)

    if @task.save
      redirect_to task_chat_rooms_path(@task)
      @status = true
    else
      render :new
      @status = false
    end
  end

   def update
     if @task.complete
       redirect_to tasks_path
     else
       render :index
     end
   end

  # DELETEs/1
  def destroy
    @task = current_user.tasks.find(params[:id])
    @task.destroy
    redirect_to user_path(current_user), notice: '削除されました'
  end

  private

  def task_params
    params.require(:task).permit(:user_id, :name)
  end
  
  def set_task
    @task = current_user.tasks.find(params[:id])
  end
  
  def check_ten_todo
    redirect_to root_path, notice: 'やりたい事は10個以上を登録できません。全行程終了してから再度お試しください。' if current_user.tasks.todo.size == 10
  end

  def set_user
    @user = User.find(params[:user_id]) if params[:user_id].present?
  end
  
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, except: [:index]
  before_action :set_todo, only: [:show, :edit, :update, :destroy, :sort]

  #endshowの工程ボタンからここへ
  def index 
    @task = Task.find(params[:task_id])
    render 'dones/show'
  end

  # GET /todos/new
  def new
    @todo = @task.todos.new
  end

  # GET /todos/1/edit
  def edit
  end
  
  def sort
  end


  # POST /todos
  def create
    @todo = @task.todos.new(todo_params)

    if @todo.save
       @status = true
    else
       @status = false
    end
  end

  # PATCH/PUT /todos/1
  def update
    if @todo.update(todo_params)
       @status = true
    else
       @status = false
    end
  end

  # DELETE /todos/1
  def destroy
    @todo.destroy
    redirect_to todos_url, notice: 'Todo was successfully destroyed.'
  end

  private

  def set_task
    @task = current_user.tasks.find_by(id: params[:task_id])
    redirect_to(tasks_url, alert: "ERROR!!") if @task.blank?
  end

  def set_todo
    @todo = @task.todos.find_by(id: params[:id])
  end


    def todo_params
      params.require(:todo).permit(:content, :task_id, :position, :done)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :authenticate_user!

  def index
    @users = params[:name].present? ? User.where('name LIKE ?', "%#{params[:name]}%") : User.none
  end
  
  def show
    @user = User.find(params[:id])
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bs4_bgcolor_for(flash_key)
     case flash_key
     when "success"
       "alert-success"
     when "error"
       "alert-danger"
     when "alert"
       "alert-warning"
     when "notice"
       "alert-info"
     else
       flash_key.to_s
     end
  end
  
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, options = { size: 80 })
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/dig_home/dig_index.html.erb
<div id="main-title">
  <h1>登録ユーザー一覧</h1>
</div>

<div id="all-user-count">
  <p>登録ユーザー:<%= User.all.size %></p><p>招待人数<%= @user.invitation %></p>
</div>
<div class="kaminari"> <%= paginate @users %> </div>

<div id="users-wrapper">
  <% @users.each do |user| %>
    <li>
      <div class="users-view">
        <div class= "users-image">
          <%= gravatar_for user, size: 80 %>
        </div>
        <div class="user-index-right">
          <h2><%= user.name %></h2>
          <%= link_to "ユーザーのページへ", user_path(user), class: "btn btn-info" %>  
        </div>   
      </div>
    </li>
  <% end %>
</div>

app/views/dig_home/dighome.html.erb
<div id="main-title">
  <h1>ホーム</h1>
</div>
<div id="nav-btn">
  <%= link_to "ユーザー一覧", dig_home_dig_index_path, class: "btn btn-primary" %>
  <%= link_to "実行したいこと", new_task_path, class: "btn btn-success" %>
  <%= link_to "自分のページ", user_path(current_user), class: "btn btn-warning" %>
  <%= link_to "みんなのやりたい事一覧", users_path, class: "btn btn-info" %>
  <%= link_to "今まで実行した事", endshow_index_path, class: "btn btn-secondary" %>
</div>
<div class="dighome wrapper">
  <div class ="dighome-menu">
    <p>追加機能メニュー</p>
    <p>簡単なゲーム</P>
    <%= link_to "簡単な戦闘", game_index_path %><br>
    <%= link_to "ゲームの種", game_path(current_user) %>
  </div>
  <div class="Introduction">
    <%= image_pack_tag "mogura-icon.jpg", width:"100px",height:"80px", alt:"モグラアイコン" %>
    <br><br>
    <h4>名前の由来はやりたいと思ってた事をDigup（掘り起こす）</h4>
    <p>ホームページは見栄え、機能もよくしていきます（その日の最初のログインの人は無料サイトなのですごく遅いです）</p>
      <div class= "dighome-item">
        <%= image_pack_tag "1796066_s.jpg", width:"640px",hight:"400px", alt:"新しい扉" %>
        <br><br>
        <h4>使用例</h4>
        <p>自分のやりたい事の整理だけで使ってくれてもいいし</p>
        <p>一緒にやってるゲームの掲示板的につかってもいいし</p>
        <p>他の人の実行した事の工程を見て自分もそれを真似てやってもいいし</p>

        <br>
        <%= image_pack_tag "hizasi_m.jpg", width:"640px",hight:"400px", alt:"木漏れ日" %>
        <br><br>
        <h4>目標は</h4>
        <p>こんなイベントをしたいから特設サイトを作りたいとか<p>
        <p>こんなサービスがあったら面白そうとか</p>
        <p>やりたい事を実現するのにどんなサイトやアプリがあれば実現しやすい</p>
        <p>という希望があれば、作れるようになれれば面白いかなと</p>
      </div>
  </div>

  <aside>
  <% @a=0 %> 
  <h5>最新の３０件</h5>
    <% @alltask.each do |task| %>
      <% if @a<30 %>
        <div class= "alltask">
          <div class="aside-name"><%= task.user&.name %></div>&nbsp:&emsp;  <div class="aside-task-name"><%= task.name %></div>
          <% @a += 1 %> 
        </div>
      <% end %>
    <% end %>
  </aside>
</div>